# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lE7wzdgVY9m09Xw0451jO20JOMQtcaJB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
df.head()

df.shape
df.info()
df.describe()

df.isnull().sum()
df.drop_duplicates(inplace=True)
df.fillna(df.mean(numeric_only=True), inplace=True)

df.describe().T

print(df.columns)

sns.histplot(df['math score'], kde=True)
plt.title('Distribution of Math Scores')
plt.show()

sns.boxplot(x=df['math score'])
plt.show()

sns.countplot(x='gender', data=df)
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap='coolwarm')
plt.show()

corr_matrix = df.corr(numeric_only=True)
corr_matrix

target_corr = df.corr(numeric_only=True)['math score'].sort_values(ascending=False)
print(target_corr)